version: "3.2"
services:

  # nginx:
    # image: nginx:stable-alpine
    # volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # networks:
      # - internal
    # ports:
      # - "80:80"
      
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./mysql/custom_my.cnf:/etc/mysql/mysql.conf.d/custom_my.cnf
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - internal
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASS=pass
      - TZ=America/Santiago
    ports:
      - "3306:3306"

  service_back:
    build: './apache2/'
    restart: always
    networks:
      - internal
    volumes:
      - ./servicios/backoffice/:/var/www/html
      - ./apache2/apache_service_back.conf:/etc/apache2/sites-available/000-default.conf
      #- ./apache2/php.ini:/etc/php/7.2/apache2/php.ini
    ports:
      - "80:80"

  # nodejs:
    # image: node:carbon-jessie
    # restart: always
    # tty: true
    # privileged: true
    # networks:
      # - internal
    # volumes:
      # - ./nodejs:/usr/src/app
    # depends_on:
      # - mysql
   
  # service_win:
    # build: './apache2/'
    # restart: always
    # networks:
      # - internal
    # volumes:
      # - ./servicios/winchile/:/var/www/html
      # - ./apache2/apache_service_win.conf:/etc/apache2/sites-available/000-default.conf
      # #- ./apache2/php.ini:/etc/php/7.2/apache2/php.ini
      
networks:
  internal:

volumes:
  mysql_vol:
  storage_vol: